services:
  apiGateway:
    container_name: APIGateway
    image: apigateway:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file: .env